/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package common.gui;

import Parent.Parent_SignUp;
import java.sql.SQLException;

/**
 *
 * @author Omer Khan
 */
public class UsersSignupScreen extends javax.swing.JFrame {

    public UsersSignupScreen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        lecturers_count8 = new javax.swing.JLabel();
        parentsbtn = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        lecturers_count9 = new javax.swing.JLabel();
        doctors = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        lecturers_count10 = new javax.swing.JLabel();
        teachers = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(251, 255, 239));

        jPanel3.setBackground(new java.awt.Color(251, 255, 239));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lecturers_count8.setFont(new java.awt.Font("Tahoma", 1, 28)); // NOI18N
        lecturers_count8.setForeground(new java.awt.Color(255, 255, 255));
        lecturers_count8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lecturers_count8.setText("PARENTS");
        lecturers_count8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lecturers_count8MouseEntered(evt);
            }
        });
        jPanel3.add(lecturers_count8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 250, 30));

        parentsbtn.setBackground(new java.awt.Color(251, 255, 239));
        parentsbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/src/resources/father-and-son.png"))); // NOI18N
        parentsbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                parentsbtnMouseClicked(evt);
            }
        });
        jPanel3.add(parentsbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 6, 270, 260));

        jPanel4.setBackground(new java.awt.Color(251, 255, 239));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lecturers_count9.setFont(new java.awt.Font("Tahoma", 1, 28)); // NOI18N
        lecturers_count9.setForeground(new java.awt.Color(255, 255, 255));
        lecturers_count9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lecturers_count9.setText("DOCTORS");
        lecturers_count9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lecturers_count9MouseEntered(evt);
            }
        });
        jPanel4.add(lecturers_count9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 250, 30));

        doctors.setIcon(new javax.swing.ImageIcon(getClass().getResource("/src/resources/doctor.png"))); // NOI18N
        doctors.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                doctorsMouseClicked(evt);
            }
        });
        jPanel4.add(doctors, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 6, 270, 260));

        jPanel5.setBackground(new java.awt.Color(251, 255, 239));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lecturers_count10.setFont(new java.awt.Font("Tahoma", 1, 28)); // NOI18N
        lecturers_count10.setForeground(new java.awt.Color(255, 255, 255));
        lecturers_count10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lecturers_count10.setText("TEACHERS");
        lecturers_count10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lecturers_count10MouseEntered(evt);
            }
        });
        jPanel5.add(lecturers_count10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 250, 30));

        teachers.setIcon(new javax.swing.ImageIcon(getClass().getResource("/src/resources/teacher (2).png"))); // NOI18N
        teachers.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                teachersMouseClicked(evt);
            }
        });
        jPanel5.add(teachers, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 6, 270, 260));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(104, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 79, -1, 290));

        jPanel2.setBackground(new java.awt.Color(51, 153, 255));

        jLabel18.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 48)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("SIGNUP");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 1117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, 68, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1120, 80));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lecturers_count8MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lecturers_count8MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_lecturers_count8MouseEntered

    private void lecturers_count9MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lecturers_count9MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_lecturers_count9MouseEntered

    private void lecturers_count10MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lecturers_count10MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_lecturers_count10MouseEntered

    private void parentsbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_parentsbtnMouseClicked
         openSignUpForm("Parent");
    }//GEN-LAST:event_parentsbtnMouseClicked

    private void teachersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_teachersMouseClicked
         openSignUpForm("Teacher");
    }//GEN-LAST:event_teachersMouseClicked

    private void doctorsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_doctorsMouseClicked
         openSignUpForm("Doctor");
    }//GEN-LAST:event_doctorsMouseClicked

  private void openSignUpForm(String role) {
        
        if(role.equals("Parent")){
            Parent.Parent_SignUp ps = new Parent_SignUp();
            ps.setVisible(true);
        }else{
            SignUp su = new SignUp();
            su.setVisible(true);
        }
        this.dispose();
    }
  
  
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel doctors;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JLabel lecturers_count10;
    private javax.swing.JLabel lecturers_count8;
    private javax.swing.JLabel lecturers_count9;
    private javax.swing.JLabel parentsbtn;
    private javax.swing.JLabel teachers;
    // End of variables declaration//GEN-END:variables
}
