/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package student;


import ui.frame.Game;

/**
 *
 * @author Omer Khan
 */
public class SelectGames extends javax.swing.JFrame {

    public SelectGames() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        parentsbtn = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        doctors = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        teachers = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        doctors1 = new javax.swing.JLabel();
        btn_Bck1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(251, 255, 239));

        jLabel18.setFont(new java.awt.Font("Imprint MT Shadow", 1, 60)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(153, 0, 0));
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("SELECT GAMES");

        jPanel3.setBackground(new java.awt.Color(251, 255, 239));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        parentsbtn.setBackground(new java.awt.Color(251, 255, 239));
        parentsbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/src/resources/colorSort2-removebg-preview.png"))); // NOI18N
        parentsbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                parentsbtnMouseClicked(evt);
            }
        });
        jPanel3.add(parentsbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 6, 270, -1));

        jPanel4.setBackground(new java.awt.Color(251, 255, 239));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        doctors.setIcon(new javax.swing.ImageIcon(getClass().getResource("/src/resources/chess3.png"))); // NOI18N
        doctors.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                doctorsMouseClicked(evt);
            }
        });
        jPanel4.add(doctors, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, -4, 270, 280));

        jPanel5.setBackground(new java.awt.Color(251, 255, 239));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        teachers.setIcon(new javax.swing.ImageIcon(getClass().getResource("/src/resources/guessTheNumber2-removebg-preview.png"))); // NOI18N
        teachers.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                teachersMouseClicked(evt);
            }
        });
        jPanel5.add(teachers, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 6, 270, 270));

        jPanel6.setBackground(new java.awt.Color(251, 255, 239));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        doctors1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/src/resources/guessWord.png"))); // NOI18N
        doctors1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                doctors1MouseClicked(evt);
            }
        });
        jPanel6.add(doctors1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, -10, 270, 290));

        btn_Bck1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/backbtn.png"))); // NOI18N
        btn_Bck1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_Bck1btn_BckMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, 318, Short.MAX_VALUE)
                .addGap(12, 12, 12))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(btn_Bck1)
                .addGap(29, 29, 29)
                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 1083, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(btn_Bck1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(33, 33, 33))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18))))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1260, 420));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void parentsbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_parentsbtnMouseClicked
     Game frame = new Game(true);
                    frame.setSize(1370,800);
                    frame.setVisible(true);
        
    }//GEN-LAST:event_parentsbtnMouseClicked

    private void teachersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_teachersMouseClicked
//         new GTN.NumberGuessingGame().setVisible(true);
//         dispose();
         
    }//GEN-LAST:event_teachersMouseClicked

    private void doctorsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_doctorsMouseClicked
         openSignUpForm("Doctor");
    }//GEN-LAST:event_doctorsMouseClicked

    private void doctors1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_doctors1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_doctors1MouseClicked

    private void btn_Bck1btn_BckMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_Bck1btn_BckMouseClicked
        StudentDashboard sd = new StudentDashboard();
        sd.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_Bck1btn_BckMouseClicked

  private void openSignUpForm(String role) {
        this.dispose();
        
    }
  
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SelectGames.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SelectGames.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SelectGames.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SelectGames.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            
            public void run() {
                    SelectGames urb =  new SelectGames();
            urb.pack(); // Adjust the size based on the components
            urb.setLocationRelativeTo(null);
            urb.setVisible(true);
        
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btn_Bck1;
    private javax.swing.JLabel doctors;
    private javax.swing.JLabel doctors1;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JLabel parentsbtn;
    private javax.swing.JLabel teachers;
    // End of variables declaration//GEN-END:variables
}
